services:
  - type: web
    name: skin-disease-detector
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app.app:app
    runtime: python
    plan: free
    branch: main
    autoDeploy: true
